name: Check code styling

on:
  push:
    branches:
    - main
    paths:
    - src/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7 environment
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Analyze python codes
      run: |
        # check all py files except for the DOPE score one
        # which needs to manually insert a license key
        # fail under 6/10
        pylint --fail-under=6 `find . -name '*.py' ! '(' -name '*DOPE*' ')'`
